package com.shiro.demo.dao;

import com.shiro.demo.entity.Perm;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PermMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_perm
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_perm
     *
     * @mbg.generated
     */
    int insert(Perm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_perm
     *
     * @mbg.generated
     */
    Perm selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_perm
     *
     * @mbg.generated
     */
    List<Perm> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_perm
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Perm record);

    List<Perm> selectByUser(@Param("userId") long userId);
}