server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://120.78.153.120:3306/mytest?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 120.78.153.120
    port: 6399
    password:
    timeout: 3000
    database: 0
    pool:
      maxTotal: 100
      maxIdle: 8
      minIdle: 0
      maxWaitMillis: 3000
      testOnBorrow: true



mybatis:
  type-aliases-package: com.shiro.demo.entity
  mapperLocations: classpath:mappers/*.xml

