package com.shiro.demo.entity;

public class Perm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_perm.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_perm.perm_name
     *
     * @mbg.generated
     */
    private String permName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_perm.perm_url
     *
     * @mbg.generated
     */
    private String permUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_perm.id
     *
     * @return the value of sys_perm.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_perm.id
     *
     * @param id the value for sys_perm.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_perm.perm_name
     *
     * @return the value of sys_perm.perm_name
     *
     * @mbg.generated
     */
    public String getPermName() {
        return permName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_perm.perm_name
     *
     * @param permName the value for sys_perm.perm_name
     *
     * @mbg.generated
     */
    public void setPermName(String permName) {
        this.permName = permName == null ? null : permName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_perm.perm_url
     *
     * @return the value of sys_perm.perm_url
     *
     * @mbg.generated
     */
    public String getPermUrl() {
        return permUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_perm.perm_url
     *
     * @param permUrl the value for sys_perm.perm_url
     *
     * @mbg.generated
     */
    public void setPermUrl(String permUrl) {
        this.permUrl = permUrl == null ? null : permUrl.trim();
    }
}